### ISSUE TITLE
Sometimes API responds with 0 intersecting parcels

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/Cityscape-API-Python-Interface#2]
When you ask the API for info about an address that's outside Cook County, you get a response that has `null` for many fields, including the `parcels_intersecting` field that's most important to this script. 

(The API isn't actually intelligent enough to know when something's outside of Cook County, because it returns the same kind of response if it just can't find the address within Cook County.)

The script needs to create a row for this response, like any other, but with a note of some kind that it couldn't be found by the API.

**Comment by easherma** [comment]
Can you add an example to sample.csv?

**Comment by easherma** [comment]
Have we fully addressed this with the no_results output?

**Comment by stevevance** [comment]
@easherma Yep.
