### ISSUE TITLE
Include "query" as a possible parameter

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/Cityscape-API-Python-Interface#4]
The Cityscape API has been updated to accept a `query` parameter and will prefer "parameter groupings" like this:
1. `pin`
2. `query`
3. `address`, `city`, and `state`

[Sample URL](http://tod.chicagocityscape.com/tod/index.php?query=153%20BRIARWOOD%20NORTH,%20OAK%20BROOK,%20IL)

**Comment by easherma** [comment]
wrote a new function that can be called to handle this specific situation
