### ISSUE TITLE
Accommodate an arbitrary "id" and include it in the output

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/Cityscape-API-Python-Interface#7]
I have a list of properties and I have an internal ID for them. There's a column for it in the input CSV, and this internal ID should maintain an association to the address/query and be included in the output CSV. 

The internal ID won't be passed along to the Cityscape API; it's a method for the user to keep track of the outputs, to see which resulting PINs are associated with my internal records. 

The column is optional in the input CSV, but ideally I want to provide these two internal columns:

| `id` | `query` |
| --- | --- |
| 596 | 9110 S 82ND AVE, HICKORY HILLS, IL 60457 |

The output would then have:

| `id` | `query` | `closest_rank` | `pin` | `city` | other columns... |
| --- | --- | --- | --- | --- | --- |
| 596 | 9110 S 82ND AVE, HICKORY HILLS, IL 60457 | 0 | 23024170240001 | Hickory Hills | ... |

**Comment by easherma** [comment]
accommodated. at the moment, output dosen't match this column order, because pandas considers the 'closest rank' to be the index and is putting it first. probably a way to fix/tweak this, we can re-open this issue or start a new one if we need to make that change.
